### ISSUE TITLE
Error installing iTemocil

### ISSUE THREAD

**Issue by alejandroleoz** [TomAnthony/homebrew-brews#1]
Hi,
I'm trying to install itemocil using this:
brew install TomAnthony/brews/itermocil

but I'm getting this error:
error: [Errno 1] Operation not permitted: '/usr/local/Cellar/itermocil/0.2.1/libexec/vendor/lib/python2.7/site-packages/PyYAML-3.11-py2.7.egg-info/PKG-INFO'

Do you have any clue about this topic?
I'm running it on OSX 10.11.4 (El Capitan).

Thanks!
Ale.

**Comment by ruudk** [comment]
The problem has been fixed in https://github.com/TomAnthony/itermocil, please run `brew update && brew install tomanthony/brews/itermocil` to retry.
