### ISSUE TITLE
Outdated homebrew formula

### ISSUE THREAD

**Issue by gsauzande** [TomAnthony/homebrew-brews#3]
The outdated formula here is causing an installation issue mentioned by multiple people in https://github.com/TomAnthony/itermocil/issues/117

I have a PR ready for this if I get the rights to push it. @TomAnthony

**Comment by katsanva** [comment]
@TomAnthony

**Comment by ruudk** [comment]
The problem has been fixed in https://github.com/TomAnthony/itermocil, please run `brew update && brew install tomanthony/brews/itermocil` to retry.
